#This workflow is used as a template to build the sfdt plugin

name: 'Build Packages'

on: 
  workflow_call:
    inputs:
      version:
        type: string
        default: ''
      publish:
        type: boolean
        default: false
      environment:
        type: string
        required: true
    secrets:
      npm-token:
        required: false

jobs:
  build:
    name: 'build packages'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: actions/checkout@v3

      - name: 'Set Git Config'
        run: |
          git config --global user.email "ubyfishcode@gmail.com"
          git config --global user.name "ubyfishcode"

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public --tag ${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}